//Auth Action Types

const GOOOGLE_LOGIN_SUCCESS='GOOGLE_LOGIN_SUCCESS';
const GOOOGLE_LOGIN_ERROR='GOOGLE_LOGIN_ERROR';
const SIGN_IN_SUCCESS='SIGN_IN_SUCCESS';
const SIGN_IN_ERROR='SIGN_IN_ERROR';
const SIGN_UP_SUCCESS='SIGN_UP_SUCCESS';
const SIGN_UP_ERROR='SIGN_IN_ERROR';
const SIGN_OUT_SUCCESS='SIGN_OUT_SUCCESS';
const GET_PROFILE_SUCCESS='GET_PROFILE_SUCCESS'
const GET_PROFILE_ERROR='GET_PROFILE_ERROR'

export const authActions={
    GOOOGLE_LOGIN_SUCCESS, GOOOGLE_LOGIN_ERROR, SIGN_IN_SUCCESS, SIGN_IN_ERROR, SIGN_UP_SUCCESS,
    SIGN_UP_ERROR, SIGN_OUT_SUCCESS, GET_PROFILE_SUCCESS, GET_PROFILE_ERROR
}

//Image Action Types

const IMAGE_UPLOAD_SUCCESS='IMAGE_UPLOAD_SUCCESS'
const IMAGE_UPLOAD_ERROR='IMAGE_UPLOAD_ERROR'
const IMAGE_SHARE_SUCCESS='IMAGE_SHARE_SUCCESS'
const IMAGE_SHARE_ERROR='IMAGE_SHARE_ERROR'
const GET_IMAGES_SUCCESS='GET_IMAGES_SUCCESS'
const GET_IMAGES_ERROR='GET_IMAGES_ERROR'
const DELETE_IMAGE_SUCCESS='DELETE_IMAGE_SUCCESS'
const DELETE_IMAGE_ERROR='DELETE_IMAGE_ERROR'

export const imageActions={
    IMAGE_SHARE_SUCCESS, IMAGE_SHARE_ERROR, IMAGE_UPLOAD_SUCCESS, IMAGE_UPLOAD_ERROR,
    GET_IMAGES_SUCCESS, GET_IMAGES_ERROR, DELETE_IMAGE_SUCCESS, DELETE_IMAGE_ERROR
}

//User Action Types

const GET_USERS_SUCCESS='GET_USERS_SUCCESS';
const GET_USERS_ERROR='GET_USERS_ERROR';

export const userActions={
    GET_USERS_SUCCESS, GET_USERS_ERROR
}

